#!/bin/bash                                    
# passing parameters to a function             
function addem {                               
if [ $# -eq 0 ] || [ $# -gt 2 ]                
then                                           
echo -1                                        
elif [ $# -eq 1 ]                              
then                                           
echo $[ $1 + $1 ]                              
else                                           
echo $[ $1 + $2 ]                              
fi                                             
}                                              
                                               
echo -n "Adding 20 and 20: "                   
value=$(addem 20 20)                           
echo $value                                    
echo -n "Let's try adding just one number(5): "
value=$(addem 5)                               
echo $value                                    
echo -n "Now trying adding no numbers: "       
value=$(addem)                                 
echo $value                                    
echo -n "Finally, try adding three numbers: "  
value=$(addem 10 15 20)                        
echo $value                                    
