#!/bin/bash                                  
# Trapping the script exit                   
#                                            
trap "echo Goodbye..." EXIT                  
trap "echo ' Crtl-C is being trapped'" SIGINT
                                             
                                             
count=1                                      
while [ $count -le 5 ]                       
do                                           
        echo "Loop #$count"                  
        sleep 2                              
        count=$[ $count + 1 ]                
done                                         
#                                            
